"""The REAL 25E precharge board seed loads + the existing lookups answer from it.

Mirrors the bundled-fixture knowledge tests (test_knowledge.py,
test_schematic_ingest.py) but exercises the seeded 25E_Precharge_Board_v2
artifacts in bench_knowledge/ (generated by bench_knowledge/seed_25e.py from the
real Altium project). Offline; no network, no model.

Provenance contract under test (same as the bundled demo):
  * the seed has REAL parts/designators/nets — but NO documented voltage/current
    limits, so get_documented_limit is a SAFE MISS for every 25E net;
  * selecting the board via FORGE_BOARD=25e auto-ingests the SchematicJSON;
  * the default bundled bq79616 demo is unaffected when FORGE_BOARD is unset.
"""

from __future__ import annotations

import json

import pytest

from orchestrator.knowledge import (
    BOARD_25E_PROFILE_PATH,
    BOARD_25E_SCHEMATIC_PATH,
    KnowledgeAdapter,
    load_board_profile,
)
from orchestrator.knowledge.bom import _active_bom_path, lookup_bom
from orchestrator.schematic.schema import SchematicJSON


# ── the seed artifacts exist and parse against the Forge schemas ──────────────

def test_25e_profile_loads_real_parts_and_nets():
    assert BOARD_25E_PROFILE_PATH.exists(), "run bench_knowledge/seed_25e.py first"
    profile = load_board_profile(BOARD_25E_PROFILE_PATH)
    assert profile.id == "25e-precharge-2026-05"
    assert not profile.is_empty
    # real designators recovered from the .SchDoc (HV precharge board parts)
    refs = {p.ref for p in profile.parts}
    assert {"U1", "U2", "K1", "F1", "J3", "R23"} <= refs
    # parts are marked as schematic-sourced provenance
    assert profile.part("K1").source == "altium_schdoc"
    # real net names from net labels / ports / power-ports
    net_ids = {n.id for n in profile.nets}
    assert {"HV+", "HV-", "GND", "12V"} <= net_ids


def test_25e_schematic_json_validates():
    assert BOARD_25E_SCHEMATIC_PATH.exists()
    sch = SchematicJSON.model_validate(
        json.loads(BOARD_25E_SCHEMATIC_PATH.read_text(encoding="utf-8"))
    )
    assert sch.schematicId == "25e-precharge-2026-05"
    assert sch.source.kind == "altium_schdoc"
    assert sch.sheetCount == 5
    assert len(sch.components) >= 60  # ~67 designated parts across 5 sheets
    assert sch.cite  # provenance present


# ── NO invented limits: every 25E net is a SAFE MISS (03 §3.3.6 / 05 §4) ──────

def test_25e_nets_carry_no_documented_limit():
    profile = load_board_profile(BOARD_25E_PROFILE_PATH)
    for net in profile.nets:
        # real-data-only: limit fields intentionally empty (like an image source)
        assert net.max_voltage_v is None
        assert net.max_current_a is None


def test_25e_documented_limit_is_safe_miss():
    ka = KnowledgeAdapter(BOARD_25E_PROFILE_PATH)
    lim = ka.get_documented_limit("HV+", "net")
    assert lim.found is False
    assert lim.maxVoltageV is None and lim.maxCurrentA is None


# ── FORGE_BOARD=25e selects the board AND auto-ingests its schematic ──────────

def test_forge_board_25e_selects_and_ingests(monkeypatch):
    monkeypatch.delenv("BOARD_PROFILE", raising=False)
    monkeypatch.delenv("BOM_FILE", raising=False)
    monkeypatch.setenv("FORGE_BOARD", "25e")

    ka = KnowledgeAdapter()
    assert ka.board_profile.id == "25e-precharge-2026-05"

    # the seeded SchematicJSON is auto-ingested (real designators + nets)
    assert ka.schematic is not None
    assert len(ka.schematic.components) >= 60

    # the EXISTING lookup_board_doc answers about a real 25E net
    res = ka.lookup_board_doc("HV+")
    assert ("net", "HV+") in [(m.kind, m.id) for m in res.profileMatches]

    # the EXISTING lookup_schematic answers about a real designator
    sch = ka.lookup_schematic("K1")
    assert "K1" in [c["ref"] for c in sch["components"]]
    assert sch["cite"]


def test_forge_board_25e_bom_has_real_designators(monkeypatch):
    monkeypatch.delenv("BOM_FILE", raising=False)
    monkeypatch.setenv("FORGE_BOARD", "25e")

    assert _active_bom_path().name.startswith("25e-precharge")
    res = lookup_bom("R23")
    assert res.matches, "expected an R23 hit in the 25E BOM"
    top = res.matches[0]
    assert top.designator == "R23"
    # REAL designators (joined on DesignItemId) — NOT inferred
    assert top.designator_inferred is False
    assert "25E" in res.cite


# ── the default bundled bq79616 demo stays intact (no FORGE_BOARD) ────────────

def test_default_demo_unaffected(monkeypatch):
    monkeypatch.delenv("FORGE_BOARD", raising=False)
    monkeypatch.delenv("BOARD_PROFILE", raising=False)
    monkeypatch.delenv("BOM_FILE", raising=False)

    ka = KnowledgeAdapter()
    assert ka.board_profile.id == "bq79616-bringup-2026-05"
    assert ka.schematic is None  # nothing auto-ingested for the demo
    # documented bq79616 limit still resolves
    lim = ka.get_documented_limit("J3", "net")
    assert lim.found is True and lim.maxVoltageV == 30.0

    # default BOM is still the AMB / bq79616 BOM
    assert _active_bom_path().name == "bq79616-bringup-bom.yaml"
    res = lookup_bom("U2")
    assert res.matches
    assert "AMB BOM" in res.cite
